### PR TITLE
feat: support divorces, add marriage information 

### PR DESCRIPTION
**Pull request by fbiville**
The existing `IS_MARRIED_TO` has been changed to `IS_SPOUSE_OF`.

`IS_SPOUSE_OF` is inferred from family's `HUSB` / `WIFE` tags.

`IS_MARRIED_TO` relationships are now only created if there are
marriage family event information (`MARR` Gedcom tag).

`DIVORCED` relationships are created from family divorce event
information (`DIV` Gedcom tag).

### CODE REVIEW

**Comment by fbiville** [comment]
Note: I'm growing skeptical about the use of present tense in the relationship types.
Do the phrasings `IS_SPOUSE_OF` and `IS_MARRIED_TO` make sense when people later divorced? Do they make for deceased people?
@dhrudevalia wdyt?

**Comment by dhrudevalia** [comment]
> Note: I'm growing skeptical about the use of present tense in the relationship types. Do the phrasings `IS_SPOUSE_OF` and `IS_MARRIED_TO` make sense when people later divorced? Do they make for deceased people? @dhrudevalia wdyt?

hmm yeah i've been thinking but not sure what the best approach would be.

Maybe `WED_TO`? `HAS_BEEN_MARRIED_TO`.

**Comment by fbiville** [comment]
Let's maybe follow up in another PR when we get rid of of `IS_`? Wdyt?

**Comment by dhrudevalia** [comment]
> Let's maybe follow up in another PR when we get rid of of `IS_`? Wdyt?

Yep that's fine with me.

**Review by dhrudevalia — APPROVED** [review]

**Pull request merged**
